spring.datasource.url=jdbc:mysql://localhost:3306/mybook_ms_core
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true

server.port=8081
server.servlet.context-path=/mbc

secret.key=mySecretKeyhgfdxcvghjkfhdxcvbnjhfdvxcbnjhgfbcvnmhjghfbcnmjkhgfbnmjkhgvbnjkhgnvbnmjkhg