POST http://localhost:8081/mbc/books/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiZXhwIjoxNzU1NTgzODk2LCJ1c2VybmFtZSI6Imlyd2FuLmRldiJ9.xhsKKtA9MqsdH-e_tx--rRITmrCu_bJyyC9XMAOi2k8

{
    "issbn":"ISB112233",
    "title":"Seni Merayu Tuhan",
    "numberOfPage":222,
    "description":"Build Human Habit for someday",
    "price":50.0,
    "publisher":"Mizan",
    "authorName":"Husein Jafar",
    "bookTypes":[
        {
            "bookTypeCode":"DMR"
        },
        {
            "bookTypeCode":"ADV"
        }
    ] 
}